config/routes.rb
Rails.application.routes.draw do


   devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about'
    post 'stadiums/:id', to: 'stadiums#create'
    resources :stadiums, only: [:index, :create, :show] do
      collection do
        get 'search'
      end
    end
    resources :posts, only: [ :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get :likes
      end
    end
  end

  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    get 'users/:id/send_off' => 'users#send_off', as: 'send_off'
    patch 'users/:id/out' => 'users#out', as: 'out'
    resources :clubs, only: [:create, :index, :edit, :update, :destroy]
    resources :stadiums, only: [:create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    get 'comments' => 'comments#index', as: 'comments'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  enum division: { choose_one: 0, division_1: 1, division_2: 2, division_3: 3 }

  validates :name, presence: true, uniqueness: true

  has_many :stadiums
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :caption, presence: true

  has_many_attached :images

  belongs_to :user
  belongs_to :stadium
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

end

app/models/stadium.rb
class Stadium < ApplicationRecord
    belongs_to :club
    has_many :posts, dependent: :destroy

    validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true, length: { in: 2..30 }
  validates :email, uniqueness: true

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.email = "guest@example.com"
    end
  end

  def active_for_authentication?
    super && (is_valid == true)
  end

end

app/controllers/admin/clubs_controller.rb
class Admin::ClubsController < ApplicationController

  before_action :correct_user

  def create
    @club = Club.new(club_params)
    if @club.save
      redirect_to admin_clubs_path
    else
      @q = Club.ransack(params[:q])
      @clubs = @q.result.page(params[:page])
      render :index
    end
  end

  def index
    @club = Club.new
    @q = Club.ransack(params[:q])
    @clubs = @q.result.page(params[:page])
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])
    if @club.update(club_params)
      redirect_to admin_clubs_path
    else
      render :edit
    end
  end

  private

  def club_params
    params.require(:club).permit(:name, :division)
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :correct_user

  def index
    @posts = Post.all.page(params[:page]).order(created_at: "DESC")
  end

  def show
    @post = Post.find(params[:id])
    @stadium = @post.stadium
    @user = @post.user
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/admin/stadiums_controller.rb
class Admin::StadiumsController < ApplicationController

  before_action :correct_user


  def create
    @stadium = Stadium.new(stadium_params)
    @club = Club.find(params[:stadium][:club_id])
    @stadium.club_id = @club.id
    if @stadium.save
      redirect_to admin_stadiums_path
    else
      @q = Stadium.ransack(params[:q])
      @stadiums = @q.result.page(params[:page])
      render :index
    end
  end

  def index
    @q = Stadium.ransack(params[:q])
    @stadiums = @q.result.page(params[:page])
    @stadium = Stadium.new
  end

  def show
    @stadium = Stadium.find(params[:id])
    @posts = @stadium.posts.page(params[:page]).order(created_at: "DESC")
  end

  def edit
    @stadium = Stadium.find(params[:id])
  end

  def update
    @stadium = Stadium.find(params[:id])
    if @stadium.update(stadium_params)
      redirect_to admin_stadium_path(@stadium)
    else
      render :edit
    end
  end

  private
  def stadium_params
    params.require(:stadium).permit(:name, :club_id)
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :correct_user
  
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def send_off
    @user = User.find(params[:id])
  end

  def out
    @user = User.find(params[:id])
    @user.update(is_valid: false)
    redirect_to admin_user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :is_valid)
  end
  
  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/clubs_helper.rb
module Admin::ClubsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/stadiums_helper.rb
module Admin::StadiumsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/stadiums/_index.html.erb
<h1>一覧</h1>
<div class="p-1">
  <%= search_form_for @q, url: admin_stadiums_path do |f| %>
  <%= f.label :name_cont, 'スタジアム名' %>
  <%= f.search_field :name_cont %>
  <%= f.submit '検索' %>　<%= link_to "一覧で表示", admin_stadiums_path %>
<% end %>
</div>
<table class="table">
    <thead>
        <tr>
            <th>スタジアム名</th>
            <th>保有チーム</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% stadiums.each do |stadium| %>
        <tr>
            <td><%= link_to stadium.name, admin_stadium_path(stadium) %></td>
            <td><%= stadium.club.name %></td>
            <td><%= link_to "編集", edit_admin_stadium_path(stadium), class: "btn btn-sm btn-success" %></td>
        </tr>
        <% end %>
        <%= paginate stadiums%>
    </tbody>
</table>

app/views/admin/stadiums/_new.html.erb
<h1>新規作成</h1>
<%= form_with model: stadium, url: admin_stadiums_path do |f| %>
<div class="p-1">
    <%= f.label :スタジアム名 %>
    <%= f.text_field :name %>
</div>
<div class="p-1">
<%= f.label :保有クラブ %>
<%= f.select :club_id, options_from_collection_for_select(Club.all, :id, :name) %>
</div>
<div class="p-1">
<%= f.submit "作成", class: "btn btn-sm btn-success" %>
<% end %>
</div>

app/views/admin/stadiums/_show.html.erb
<h2><%= stadium.name %></h2>
<p>保有クラブ：<%= stadium.club.name %></p>
<% if admin_signed_in? %>
<%= link_to "スタジアムの編集", edit_admin_stadium_path, class: "btn btn-sm btn-success" %>
<%= link_to "スタジアムの一覧", admin_stadiums_path, class: "btn btn-sm btn-info" %>
<% end %>

app/views/admin/stadiums/edit.html.erb
<div class="container">
  <div class="row">
    <div class="px-auto">
      <h1><%= @stadium.name %>の編集</h1>
      <%= form_with model: @stadium, url: admin_stadium_path do |f| %>
        <div class="p-1">
          <%= f.label :スタジアム名 %>
          <%= f.text_field :name %>
        </div>
        <div class="p-1">
          <%= f.label :保有クラブ %>
          <%= f.select :club_id, options_from_collection_for_select(Club.all, :id, :name) %>
        </div>
        <div class="p-1">
          <%= f.submit "更新", class: "btn btn-sm btn-success" %>
        </div>
      <% end %>
      <div class="p-1">
        <%= link_to "スタジアムの詳細", admin_stadium_path(@stadium), class: "btn btn-sm btn-primary" %>
        <%= link_to "スタジアムの一覧", admin_stadiums_path, class: "btn btn-sm btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/stadiums/index.html.erb
<div class="container">
  <div class="row" %>
    <div class="col-md-4">
      <%= render 'layouts/error_messages', model: @stadium %>
      <%= render 'new', stadium: @stadium %>
    </div>

    <div class="col-md-8">
      <%= render 'index',stadiums: @stadiums %>
    </div>
  </div>
</div>

app/views/admin/stadiums/show.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto p-1">
      <%= render 'show', stadium: @stadium %>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto p-2">
      <%= render 'public/posts/index', posts: @posts %>
    </div>
  </div>
</div>