config/routes.rb
Rails.application.routes.draw do


   devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about'
    post 'stadiums/:id', to: 'stadiums#create'
    resources :stadiums, only: [:index, :create, :show] do
      collection do
        get 'search'
      end
    end
    resources :posts, only: [ :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get :likes
      end
    end
  end

  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    get 'users/:id/send_off' => 'users#send_off', as: 'send_off'
    patch 'users/:id/out' => 'users#out', as: 'out'
    resources :clubs, only: [:create, :index, :edit, :update, :destroy]
    resources :stadiums, only: [:create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    get 'comments' => 'comments#index', as: 'comments'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  enum division: { choose_one: 0, division_1: 1, division_2: 2, division_3: 3 }

  validates :name, presence: true, uniqueness: true

  has_many :stadiums
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :caption, presence: true

  has_many_attached :images

  belongs_to :user
  belongs_to :stadium
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

end

app/models/stadium.rb
class Stadium < ApplicationRecord
    belongs_to :club
    has_many :posts, dependent: :destroy

    validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true, length: { in: 2..30 }
  validates :email, uniqueness: true

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.email = "guest@example.com"
    end
  end

  def active_for_authentication?
    super && (is_valid == true)
  end

end

app/controllers/admin/clubs_controller.rb
class Admin::ClubsController < ApplicationController

  before_action :correct_user

  def create
    @club = Club.new(club_params)
    if @club.save
      redirect_to admin_clubs_path
    else
      @q = Club.ransack(params[:q])
      @clubs = @q.result.page(params[:page])
      render :index
    end
  end

  def index
    @club = Club.new
    @q = Club.ransack(params[:q])
    @clubs = @q.result.page(params[:page])
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])
    if @club.update(club_params)
      redirect_to admin_clubs_path
    else
      render :edit
    end
  end

  private

  def club_params
    params.require(:club).permit(:name, :division)
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  before_action :correct_user

  def index
    @q = Comment.ransack(params[:q])
    @comments = @q.result.page(params[:page]).order(created_at: "DESC")
  end

  def create
    post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.post_id = post.id
    if comment.save
      redirect_to admin_post_path(post)
    else
      render :show
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    comment.destroy
    redirect_to admin_post_path(post)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :correct_user

  def index
    @posts = Post.all.page(params[:page]).order(created_at: "DESC")
  end

  def show
    @post = Post.find(params[:id])
    @stadium = @post.stadium
    @user = @post.user
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :correct_user
  
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def send_off
    @user = User.find(params[:id])
  end

  def out
    @user = User.find(params[:id])
    @user.update(is_valid: false)
    redirect_to admin_user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :is_valid)
  end
  
  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/clubs_helper.rb
module Admin::ClubsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/stadiums_helper.rb
module Admin::StadiumsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/clubs/_index.html.erb
<h1>クラブ一覧</h1>
<div class="p-1">
  <%= search_form_for @q, url: admin_clubs_path do |f| %>
    <%= f.label :name_cont, 'クラブ名' %>
    <%= f.search_field :name_cont %>
    <%= f.submit '検索' %>　<%= link_to "一覧で表示", admin_clubs_path %>
  <% end %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>クラブ名</th>
      <th>スタジアム</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% clubs.each do |club| %>
    <tr>
      <td><%= club.name %></td>
      <td>
        <% club.stadiums.each do |stadium| %>
          <%= link_to admin_stadium_path(stadium) do %>
            <%= stadium.name %><br>
          <% end %>
        <% end %>
      </td>
      <% if admin_signed_in? %>
      <td>
        <%= link_to "編集", edit_admin_club_path(club), class: "btn btn-sm btn-success" %>
      </td>
      <% end %>
    </tr>
    <% end %>
    <%= paginate clubs %>
  </tbody>
</table>

app/views/admin/clubs/_new.html.erb
<h1 >クラブの新規作成</h1>
<div>
  <%= form_with model: club, url: admin_clubs_path do |f| %>
  <div class="p-1">
  <%= f.label :クラブ名 %>
  <%= f.text_field :name %>
  </div>
  <div class="p-1">
  <%= f.label :所属リーグ %>
  <%= f.select :division, Club.divisions.keys.map {|k| [I18n.t("enums.club.division.#{k}"), k]} %>
  </div>
  <div class="p-1">
  <%= f.submit "保存" %>
  <% end %>
  </div>
</div>

app/views/admin/clubs/_show.html.erb
<h1><%= club.name %></h1>
<p>所属リーグ：<%= club.division_i18n %></p>
<h5>保有スタジアム</h5>
<% stadiums.each do |stadium| %>
  <%= stadium.name %>
<% end %>
<div>
<% if admin_signed_in? %>
  <%= link_to "クラブの編集", edit_admin_club_path(club) %>
  <%= link_to "クラブの一覧", admin_clubs_path %>
<% end %>
</div>

app/views/admin/clubs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="px-auto">
      <h1><%= @club.name %>の情報編集</h1>
      <%= form_with model: @club, url: admin_club_path do |f| %>
        <div class="p-1">
          <%= f.label :クラブ名 %>
          <%= f.text_field :name %>
        </div>
        <div class="p-1">
          <%= f.label :所属リーグ %>
          <%= f.select :division, Club.divisions.keys.map {|k| [I18n.t("enums.club.division.#{k}"), k]} %>
        </div>
        <div class="p-1">
          <%= f.submit "保存", class: "btn btn-sm btn-success" %>
        </div>
        <% end %>
        <div class="p-1">
        <%= link_to "クラブの一覧", admin_clubs_path, class: "btn btn-sm btn-info" %>
        </div>
    </div>
  </div>
</div>

app/views/admin/clubs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= render 'layouts/error_messages', model: @club %>
      <%= render 'new', club: @club %>
    </div>

    <div class="col-md-8">
      <%= render 'index', clubs: @clubs %>
    </div>
  </div>
</div>

app/views/admin/clubs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= render 'show', { club: @club, stadiums: @stadiums } %>
    </div>
  </div>
</div>

app/views/admin/comments/_comment.html.erb
<h3>コメント</h3>
  <div class="p-1">
    <p>コメント数：<%= post.comments.count %>件</p>
    <% post.comments.each do |comment| %>
      <div class="p-1">
        <%= link_to comment.user.name, admin_user_path(comment.user) %>
        <%= comment.comment %>
        <%= comment.created_at.strftime('%Y/%m/%d %-H:%M') %>
        <%= link_to "削除", admin_post_comment_path(comment.post, comment), method: :delete %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <div class="p-1 text-center">
        <%= search_form_for @q, url: admin_comments_path do |f| %>
          <%= f.search_field :comment_cont, placeholder: "コメントを入力" %>
          <%= f.submit '検索' %>　<%= link_to "コメント一覧を表示", admin_comments_path %>
        <% end %>
      </div>
      <div class="p-3">
        <h3>コメント一覧</h3>
        <table class="table">
          <thead>
            <tr>
              <th>ユーザー</th>
              <th>コメント</th>
              <th>投稿</th>
              <th>日時</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @comments.each do |comment| %>
            <tr>
              <td><%= link_to comment.user.name, admin_user_path(comment.user) %></td>
              <td><%= comment.comment %></td>
              <td><%= link_to comment.post.title, admin_post_path(comment.post) %></td>
              <td><%= comment.created_at.strftime('%Y/%-m/%-d %-H:%M') %></td>
              <td><%= link_to "削除", admin_post_comment_path(comment.post, comment), method: :delete, class: "btn btn-sm btn-danger" %></td>
            </tr>
            <% end %>
            <%= paginate @comments %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto p-5">
      <h1>管理者トップページ</h1>
      <div class="pt-5">
        <%= link_to "ログイン", new_admin_session_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto" style="width:80%;">
      <%= render 'public/posts/index', posts: @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div>
        <%= render 'public/posts/show', post: @post %>
      </div>
      <div class="p-2">
        <%= link_to @stadium.name, admin_stadium_path(@stadium), class: "btn btn-sm btn-info" %>
        <%= link_to "投稿の一覧へ", admin_posts_path, class: "btn btn-sm btn-primary" %>
        <%= link_to "削除", admin_post_path(@post), method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-center">
      <%= render 'admin/comments/comment', {post: @post, comment: @comment} %>
    </div>
  </div>
</div>

app/views/admin/users/_user_info.html.erb
<h1 class="text-center"><%= user.name %></h1>
<div class="mx-auto p-1", style="width: 60%;">
  <%= user.introduction %>
</div>
<p class="text-center text-danger">
  <% if user.is_valid  %>
  <% else %>
    退場
  <% end %>
</p>
<div class="text-center">
  <%= link_to "編集", edit_admin_user_path(user), class: "btn btn-sm btn-success" %>
  <%= link_to "ユーザーの強制退会", admin_send_off_path(user) , class: "btn btn-sm btn-danger" %>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h3>ユーザー情報の編集</h3>
      <div>
        <%= render 'layouts/error_messages', model: @user %>
      </div>
      <div>
        <%= form_with model: @user, url: admin_user_path do |f| %>
          <div class="p-1">
            <%= f.label :ユーザーネーム %><br>
            <%= f.text_field :name %>
          </div>
          <div class="p-1">
            <%= f.label :自己紹介 %><br>
            <%= f.text_area :introduction %>
          </div>
          <div class="p-1">
            <%= f.select :is_valid, [['有効', true], ['退場', false]] %>
          </div>
          <div class="p-1">
            <%= f.submit "変更を保存", class: "btn btn-sm btn-success" %>
          </div>
        <% end %>
      </div>
      <div class="p-1">
        <%= link_to "戻る", admin_user_path(@user), class: "btn btn-sm btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="p-3 mx-auto">
      <h1>ユーザー一覧</h1>
      <table class="table">
        <thead>
          <tr>
            <th>ユーザーID</th>
            <th>ユーザーネーム</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td>
                <%= link_to admin_user_path(user) do %>
                <%= user.name %>
                <% end %>
              </td>
              <td class="text-danger">
                <% if user.is_valid  %>
                <% else %>
                  退場
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/send_off.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h3><%= @user.name %>の強制退会</h3>
      <div class="p-1 text-center">
        <%= link_to "退会させる", admin_out_path(@user), method: :patch, data: { confirm: "本当に退会させますか？"}, class: "btn btn-sm btn-danger" %>
        <%= link_to "退会させない", admin_user_path(@user), class: "btn btn-sm btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= render 'user_info', user: @user %>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto pt-5">
      <%= render 'public/posts/index', posts: @posts %>
    </div>
  </div>
</div>