config/routes.rb
Rails.application.routes.draw do


   devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about'
    post 'stadiums/:id', to: 'stadiums#create'
    resources :stadiums, only: [:index, :create, :show] do
      collection do
        get 'search'
      end
    end
    resources :posts, only: [ :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get :likes
      end
    end
  end

  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    get 'users/:id/send_off' => 'users#send_off', as: 'send_off'
    patch 'users/:id/out' => 'users#out', as: 'out'
    resources :clubs, only: [:create, :index, :edit, :update, :destroy]
    resources :stadiums, only: [:create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    get 'comments' => 'comments#index', as: 'comments'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  enum division: { choose_one: 0, division_1: 1, division_2: 2, division_3: 3 }

  validates :name, presence: true, uniqueness: true

  has_many :stadiums
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :caption, presence: true

  has_many_attached :images

  belongs_to :user
  belongs_to :stadium
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

end

app/models/stadium.rb
class Stadium < ApplicationRecord
    belongs_to :club
    has_many :posts, dependent: :destroy

    validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true, length: { in: 2..30 }
  validates :email, uniqueness: true

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.email = "guest@example.com"
    end
  end

  def active_for_authentication?
    super && (is_valid == true)
  end

end

app/controllers/admin/clubs_controller.rb
class Admin::ClubsController < ApplicationController

  before_action :correct_user

  def create
    @club = Club.new(club_params)
    if @club.save
      redirect_to admin_clubs_path
    else
      @q = Club.ransack(params[:q])
      @clubs = @q.result.page(params[:page])
      render :index
    end
  end

  def index
    @club = Club.new
    @q = Club.ransack(params[:q])
    @clubs = @q.result.page(params[:page])
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])
    if @club.update(club_params)
      redirect_to admin_clubs_path
    else
      render :edit
    end
  end

  private

  def club_params
    params.require(:club).permit(:name, :division)
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :correct_user

  def index
    @posts = Post.all.page(params[:page]).order(created_at: "DESC")
  end

  def show
    @post = Post.find(params[:id])
    @stadium = @post.stadium
    @user = @post.user
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def correct_user
    if admin_signed_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/clubs_helper.rb
module Admin::ClubsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/stadiums_helper.rb
module Admin::StadiumsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Possibility</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_clubs_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-tshirt"></i>クラブ一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_stadiums_path,class: 'nav-link text-light' do %>
              <i class="fas fa-futbol"></i></i> スタジアム一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_posts_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> 投稿一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_comments_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> コメント一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_users_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> ユーザー一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_admin_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class='container mt-5'>
	<div class='row'>
  	<div class='mx-auto'>
  		<p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/layouts/_user_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">Possibility</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <% unless current_user.email == "guest@example.com" %>
              <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
                <i class="fas fa-user"></i> マイページ
              <% end %>
            <% end %>
          </li>
          <li>
            <%=  link_to stadiums_path,class: 'nav-link text-light' do %>
              <i class="fas fa-futbol"></i></i> スタジアム一覧
            <% end %>
          </li>
          <li>
            <%=  link_to about_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
          <li>
            <%= link_to users_guest_sign_in_path, method: :post,class: 'nav-link text-light' do %>
              <i class="fas fa-address-card"></i> ゲストログイン（閲覧のみ）
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Possibility</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user == nil && current_admin == nil %>
        <%= render 'layouts/user_header' %>
      <% elsif current_user == nil && current_admin.present? %>
        <%= render 'layouts/admin_header' %>
      <% else current_user == true && current_admin == nil %>
        <%= render 'layouts/user_header' %>
      <% end %>
    </header>
    <main>
        <p class="notice text-success"><%= notice %></p>
        <p class="alert text-danger"><%= alert %></p>
        <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>